# Set the default log level to INFO
org.slf4j.simpleLogger.defaultLogLevel=info

# Set the log level for BlockHound to the most verbose
org.slf4j.simpleLogger.log.reactor.blockhound=trace

# Show thread names in the output
org.slf4j.simpleLogger.showThreadName=true
